### PR TITLE
commented out tests that are raising issues

### PR DESCRIPTION
**Pull request by BilobedCarton**
I commented out the strangely conflicting tests and fixed some remaining issues with primitive type testing. Let me know if anything should change...

### CODE REVIEW

**Comment by DamienDumayas** [comment]
The bool tests are ruining the tests because there are only two values (check contains tests).

**Comment by BilobedCarton** [comment]
Can you merge this in and then delete the // out lines. The updated condition for the test only applies for bools and we need to have the 6th input value in the primitive array test calls in main.

**Comment by BilobedCarton** [comment]
Or just add the 6th input value yourself...

**Comment by DamienDumayas** [comment]
My bad. I was in class. Send more pull requests that get rid of conflicting merge requests

**Pull request merged**
